import type { PrimeMartTemplateData } from "@/types/index";

export const placeholder: PrimeMartTemplateData = {
  brandName: "PrimeMart",

  departments: [
    { departmentLabel: "Noise Cancelling Headphones" },
    { departmentLabel: "Over-Ear Headphones" },
    { departmentLabel: "On-Ear Headphones" },
    { departmentLabel: "Earbuds & In-Ear" },
    { departmentLabel: "Headphone Amps & DACs" },
  ],
  brands: [
    { brandLabel: "Sony" },
    { brandLabel: "Bose" },
    { brandLabel: "Apple" },
    { brandLabel: "Sennheiser" },
    { brandLabel: "Anker Soundcore" },
    { brandLabel: "JBL" },
    { brandLabel: "Audio-Technica" },
  ],

  products: [
    {
      productId: "sony-wh-1000xm5",
      productTitle: "Sony WH-1000XM5 Wireless Industry Leading Noise Canceling Headphones with Auto NC Optimizer, 30hr Battery Life, Crystal Clear Hands-Free Calling",
      productListPrice: "$399.99",
      productCurrentPrice: "$298.00",
      productDiscount: "-25%",
      productRating: 4.8,
      productReviewsCount: 24518,
      productSalesVolume: "10K+ bought in past month",
      productDeliveryDate: "Tomorrow, Oct 24",
      productBadgeText: "#1 Best Seller",
      productPrimaryImage:
        "https://lh3.googleusercontent.com/aida-public/AB6AXuAz6UM0lkVtJ34Zgo3L0q0PDPklNU2ssEE3xCeIOT6tsboxSo-L-nGMGgY38XtaPdtl7hsfVgaWxM3W5iapm4RBW5ibRYlofxgJhaJ0GjZ2gle8Ku11dAA3frOZobvrq2lTp96hzN6rx724XVQvpIF-MY3g8_AhrRef6V_BpTyYjFTLSY4NQsa2NQrvloSr6CJV-yAetEHCQhQYUffDw1RHocK226-CKVnqcjf5YMo0CvpirN2Hj_nIkQ",
      productColorSwatches: ["#000000", "#cbd5e1", "#172554"],
      productKeySpecs: [
        "Two processors & 8 microphones for unprecedented ANC",
        "Up to 30-hour battery life with quick charging",
        "Multipoint connection allows switching between two devices",
        "Intuitive touch controls for pause, skip, and volume",
      ],
    },
    {
      productId: "bose-quietcomfort-ultra",
      productTitle: "Bose QuietComfort Ultra Wireless Noise Cancelling Headphones with Spatial Audio, World-Class Quiet & CustomTune Technology",
      productListPrice: "$429.00",
      productCurrentPrice: "$379.00",
      productDiscount: "-12%",
      productRating: 4.7,
      productReviewsCount: 14210,
      productSalesVolume: "8K+ bought in past month",
      productDeliveryDate: "Tomorrow, Oct 24",
      productBadgeText: "Overall Pick",
      productPrimaryImage:
        "https://lh3.googleusercontent.com/aida-public/AB6AXuClu2MHewQLR2EjFOJCy_79wyqEOkQn0GNKP--4takzG89aITzxLx1pITb_zupXoX4hpDRxgrP8eDf-w6z773Ug7wE8NR9kE-m5hcqYR0bnKhKbOIV1wOUH0i8UAkeseOGAtsSn8Mt3gnEl9Qxh_XZNQIWE9qygDVCrvI3tSr73A5zOPkEKX0HvbHwypZhKxpzB4R9e-e01QnR76CrI12FdIZ2sS8D-mTNgtSIzT2Sy23kZoySvI7ouSw",
      productColorSwatches: ["#f5f5f4", "#000000", "#fef3c7"],
      productKeySpecs: [
        "Revolutionary Bose Immersive Audio with spatial soundstage",
        "CustomTune sound calibration automatically tailors audio",
        "24 hours of continuous playback",
        "Quiet, Aware, and Immersion modes with Wind Block",
      ],
    },
    {
      productId: "apple-airpods-max",
      productTitle: "Apple AirPods Max Wireless Over-Ear Headphones, Active Noise Cancelling, Transparency Mode, Personalized Spatial Audio, Dolby Atmos",
      productListPrice: "$549.00",
      productCurrentPrice: "$479.00",
      productDiscount: "-13%",
      productRating: 4.6,
      productReviewsCount: 19832,
      productSalesVolume: "5K+ bought in past month",
      productDeliveryDate: "Friday, Oct 25",
      productBadgeText: "Premium Pick",
      productPrimaryImage:
        "https://lh3.googleusercontent.com/aida-public/AB6AXuCDHAN-21e0Q0FEmV8m1l3O5-VhZ17gVWVN4B-r6OSMCBDwVIYKhLNSQPjcA86SBGeiiDRlgTp0Q_ibxl-2K1GSoJz_91P28AFrBNR9b3UTf3G2hUSxtE7AOTkfbYl_QkmOFJhxbnfcP1FELDoSkkzrEmi7QPcN7j-Z8nW7wUC6MiYyybGcjKHfJFN5-Qahx5q5C7YkFWCXZj1g2nHx2jdsc0ao65Q572XGD2yRpWVviiV8UHaCY0TM9A",
      productColorSwatches: ["#44403c", "#cbd5e1", "#7dd3fc", "#f9a8d4"],
      productKeySpecs: [
        "Apple-designed dynamic driver delivers high-fidelity sound",
        "Computational audio combines acoustic design with H1 chips",
        "Knit-mesh canopy and memory foam ear cushions",
        "20 hours of listening with Active Noise Cancellation",
      ],
    },
    {
      productId: "anker-soundcore-life-q30",
      productTitle: "Anker Soundcore Life Q30 Hybrid Active Noise Cancelling Headphones with Multiple Modes, Hi-Res Audio, 40H Playtime, Custom EQ App",
      productListPrice: "$79.99",
      productCurrentPrice: "$59.99",
      productDiscount: "-25%",
      productRating: 4.6,
      productReviewsCount: 58914,
      productSalesVolume: "15K+ bought in past month",
      productDeliveryDate: "Tomorrow, Oct 24",
      productBadgeText: "Lightning Deal",
      productPrimaryImage:
        "https://lh3.googleusercontent.com/aida-public/AB6AXuAstKFzcT6d1bfghUQ990IS0mEIU8Q7S0co435tyuI4asfBYSN06eARZe6dA45FRcvrRKTBNDKD8gkDB7idPHss9rtPOXN-Ti9i5qTq93kz_k1knR3lUu2zY4Qdv50svvMFq_zxt6QMKdX9Y3s3Q-n8Vg4edM6Eeocy8vw5DnGVDzBZBfKS5G4cMvhsARxyRbK-FrA-ZmUKzY5IA3goz2dZ7X966GKyDxgTMZgw5njI5EyHyEggWlpmKg",
      productColorSwatches: ["#171717", "#1e3a8a", "#ffe4e6"],
      productKeySpecs: [
        "Top-Rated Budget ANC with dual noise-detecting microphones",
        "40-hour playtime in ANC mode and 60 hours standard",
        "Transport, Outdoor, and Indoor cancellation profiles",
        "NFC Fast Pairing and Soundcore custom equalizer app",
      ],
    },
    {
      productId: "sennheiser-momentum-4",
      productTitle: "Sennheiser Momentum 4 Wireless Bluetooth Headphones with Adaptive Noise Cancellation, 60-Hour Battery Life, Audiophile 42mm Transducer System",
      productListPrice: "$379.95",
      productCurrentPrice: "$269.95",
      productDiscount: "-31%",
      productRating: 4.7,
      productReviewsCount: 8340,
      productSalesVolume: "3K+ bought in past month",
      productDeliveryDate: "Tomorrow, Oct 24",
      productBadgeText: "Audiophile Pick",
      productPrimaryImage:
        "https://lh3.googleusercontent.com/aida-public/AB6AXuCDQ4AM_3PCPp4-jS1DjIiczvsxYAxdkc_3NG_XzSORR4ai7GapMP-DgU-WmD-CY09GDma8J8K5frvqvXZBDpC98hFo6OqZEKS4n7mNnp0blBTfQuTgXaAzZNrI4CAtlMhGCOmWXPUdny-sxz5fdV_y-wl2_0XaFrMxS9qV09LK91wLFYWmzUBVPX-3osAIDAC9HfBPH-XsDkym7PPaU6TubgJ55ebpG5U8CLEm2evId7nx9h86nksjJw",
      productColorSwatches: ["#171717", "#e4e4e7", "#451a03"],
      productKeySpecs: [
        "Industry-leading 60-hour battery life on a single charge",
        "Audiophile-inspired 42mm transducer system",
        "Adaptive Noise Cancellation with adjustable Transparency",
        "Smart Pause stops music when headphones are removed",
      ],
    },
  ],
};
