import type { Metadata } from "next";
import "./globals.css";
import Navbar from '../components/landing/Navbar';
import Footer from '../components/landing/Footer';
import WebGLBackground from "../components/landing/WebGLBackground";
import ChatbotPanel from "../components/ChatbotPanel";
import  logo  from '../../public/icon/logo.png';
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
       >
      <head>
        <meta charSet="utf-8" />
        <meta content="width=device-width, initial-scale=1.0" name="viewport" />
        <link rel="icon" href={logo.src} />
      </head>
      <body className="min-h-screen flex flex-col bg-background">
        <div className="fixed inset-0 pointer-events-none bg-grid -z-20"></div>
        <Navbar />
        <WebGLBackground />
        {children}
        <Footer />
        <ChatbotPanel />
      </body>
    </html>
  );
}
