import type { Metadata } from "next";
import "./globals.css";
import { Geist, Hanken_Grotesk, JetBrains_Mono } from 'next/font/google';
import Navbar from './components/Navbar';
import Footer from './components/Footer';
import WebGLBackground from "./components/WebGLBackground";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// 1. Declare each font as an independent const in the module scope
const geist = Geist({ subsets: ['latin'] });
const hankenGrotesk = Hanken_Grotesk({ subsets: ['latin'] });
const jetBrainsMono = JetBrains_Mono({ subsets: ['latin'] });
// 2. Map them to your export object afterwards
export const fonts = {
  geist,
  hankenGrotesk,
  jetBrainsMono,
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
       >
      <head>
        <meta charSet="utf-8" />
        <meta content="width=device-width, initial-scale=1.0" name="viewport" />
      </head>
      <body className="min-h-full flex flex-col bg-back">
        <div className="fixed inset-0 pointer-events-none bg-grid -z-20"></div>
        <Navbar />
        <WebGLBackground />
        {children}
        <Footer />
      </body>
    </html>
  );
}
