import type { OmniCorpRequisitionsTemplateData } from "@/types/index";



/** Raw template content. Derived fields (filterGroups, totalRequisitions) are computed in `page.tsx`. */
export const placeholder: Omit<
  OmniCorpRequisitionsTemplateData,
  "filterGroups" | "totalRequisitions"
> = {
  defaultOpenGroups: { seniority: true, workplace: true, department: true, employment: true, date: true },

  cardLabels: {
    cardReqIdPrefix: "Req ID:",
    cardQualificationsHeading: "Key Qualifications & Thresholds",
    cardCandidateCountSuffix: "Candidates In Review",
    cardViewDetailsLabel: "View Details",
    cardQuickApplyLabel: "Quick Apply",
    cardExecutiveApplyLabel: "Apply via Executive Search",
    cardSaveLabel: "Bookmark requisition",
    cardUnsaveLabel: "Remove bookmark",
    cardShareLabel: "Share requisition",
  },

  requisitions: [
    {
      requisitionId: "oc-89241",
      requisitionTitle: "Principal Cloud Infrastructure Architect",
      requisitionBadge: "Priority Hire",
      requisitionDepartment: "cloud",
      requisitionDepartmentLabel: "Core Global Platforms & Reliability",

      requisitionLocation: "New York, NY",
      requisitionWorkplace: "hybrid",
      requisitionWorkplaceLabel: "Hybrid · 3 Days",
      requisitionCompensation: "$210,000 - $265,000 USD / yr + 25% Target Bonus",
      requisitionCompensationValue: 265000,
      requisitionEmploymentType: "fte",
      requisitionEmploymentLabel: "Full-Time · Exempt",
      requisitionPostedDays: 2,
      requisitionPostedLabel: "Posted 2 days ago",
      requisitionSeniority: "lead",
      requisitionSeniorityLabel: "Lead / Principal",
      requisitionQualifications: [
        "10+ years of distributed systems engineering experience with multi-region Kubernetes orchestration and Terraform automation at petabyte scale.",
        "Proven track record managing zero-downtime microservices maintaining 99.999% SLA availability under high-frequency transaction loads.",
        "Master's or Bachelor's in CS/Software Engineering with active proficiency in Go, Rust, or modern C++ architectures.",
      ],
      requisitionStatus: "ATS Express Screening Active",
      requisitionCandidateCount: 48,
    },
    {
      requisitionId: "oc-91402",
      requisitionTitle: "VP, Global Treasury & Capital Markets",
      requisitionBadge: "Retained Search",
      requisitionDepartment: "fintech",
      requisitionDepartmentLabel: "Corporate Finance & Strategy",
      requisitionLocation: "New York, NY",
      requisitionWorkplace: "onsite",
      requisitionWorkplaceLabel: "On-site HQ · Wall St",
      requisitionCompensation: "$290,000 - $380,000 USD / yr + LTI Equity",
      requisitionCompensationValue: 380000,
      requisitionEmploymentType: "executive",
      requisitionEmploymentLabel: "Executive FTE · Officer Grade",
      requisitionPostedDays: 3,
      requisitionPostedLabel: "Posted 3 days ago",
      requisitionSeniority: "director",
      requisitionSeniorityLabel: "Director / Executive",
      requisitionIcon: "finance",
      requisitionIconTone: "navy",
      requisitionQualifications: [
        "12+ years heading corporate treasury, debt capital syndications, and global foreign exchange hedging for Fortune 100 balance sheets.",
        "Extensive direct governance experience managing $15B+ liquidity facilities alongside Tier-1 central banking counterparties.",
        "CFA and/or CPA accreditation required; advanced degree in Computational Finance or MBA preferred.",
      ],
      requisitionStatus: "Executive Confidential Disclosure Required",
    },
    {
      requisitionId: "oc-77419",
      requisitionTitle: "Senior Staff Distributed Backend Engineer (FinTech Engine)",
      requisitionBadge: "Direct Opening",
      requisitionDepartment: "fintech",
      requisitionDepartmentLabel: "Enterprise FinTech & Clearing Operations",
      requisitionLocation: "New York, NY",
      requisitionWorkplace: "hybrid",
      requisitionWorkplaceLabel: "Hybrid · 2 Days",
      requisitionCompensation: "$195,000 - $245,000 USD / yr + RSUs",
      requisitionCompensationValue: 245000,
      requisitionEmploymentType: "fte",
      requisitionEmploymentLabel: "Full-Time · Permanent",
      requisitionPostedDays: 1,
      requisitionPostedLabel: "Posted 1 day ago",
      requisitionSeniority: "lead",
      requisitionSeniorityLabel: "Lead / Principal",
      requisitionIcon: "terminal",
      requisitionIconTone: "pale",
      requisitionQualifications: [
        "8+ years building mission-critical financial ledger pipelines, double-entry processing engines, or high-throughput settlement systems.",
        "In-depth expertise in Apache Kafka, event sourcing patterns, and sub-millisecond database concurrency models.",
        "Working knowledge of ACH, SWIFT ISO-20022 formats, and SOC-1/SOC-2 Type II audit compliance.",
      ],
      requisitionStatus: "Direct Hiring Manager Review Guaranteed",
    },
    {
      requisitionId: "oc-66381",
      requisitionTitle: "Director of Global Regulatory Affairs & Data Privacy",
      requisitionBadge: "Corporate Governance",
      requisitionDepartment: "legal",
      requisitionDepartmentLabel: "Legal, Risk & Compliance Office",
      requisitionLocation: "New York, NY / Washington, DC",
      requisitionWorkplace: "hybrid",
      requisitionWorkplaceLabel: "Hybrid",
      requisitionCompensation: "$240,000 - $310,000 USD / yr",
      requisitionCompensationValue: 310000,
      requisitionEmploymentType: "executive",
      requisitionEmploymentLabel: "Full-Time · Officer Track",
      requisitionPostedDays: 4,
      requisitionPostedLabel: "Posted 4 days ago",
      requisitionSeniority: "director",
      requisitionSeniorityLabel: "Director / Executive",
      requisitionIcon: "legal",
      requisitionIconTone: "slate",
      requisitionQualifications: [
        "Juris Doctor with active bar admission and 9+ years advising multinational enterprises on data sovereignty and GDPR/CCPA statutes.",
        "Demonstrated liaison experience with FTC, SEC, and EU Data Protection Authorities on enterprise information risk disclosures.",
        "Direct oversight experience leading HIPAA, PCI-DSS Level 1, and global AI governance audits.",
      ],
      requisitionStatus: "Mandatory Background Verification Stage 4",
    },
    {
      requisitionId: "oc-54210",
      requisitionTitle: "Lead AI Systems Operations & ML Infrastructure Engineer",
      requisitionBadge: "New Requisition",
      requisitionDepartment: "cloud",
      requisitionDepartmentLabel: "Applied Research & Automation Lab",
      requisitionLocation: "New York, NY",
      requisitionWorkplace: "hybrid",
      requisitionWorkplaceLabel: "Hybrid · 3 Days",
      requisitionCompensation: "$200,000 - $250,000 USD / yr + Compute Bonus",
      requisitionCompensationValue: 250000,
      requisitionEmploymentType: "fte",
      requisitionEmploymentLabel: "Full-Time · Permanent",
      requisitionPostedDays: 0,
      requisitionPostedLabel: "Posted Today",
      requisitionSeniority: "lead",
      requisitionSeniorityLabel: "Lead / Principal",
      requisitionIcon: "ai",
      requisitionIconTone: "blue",
      requisitionQualifications: [
        "7+ years managing distributed GPU clusters, InfiniBand fabric networks, and Ray compute jobs.",
        "Extensive background setting up LLM fine-tuning, model quantization, and real-time inference telemetry.",
        "B.S. or M.S. in Computer Science with documented enterprise multimodal training deployments.",
      ],
      requisitionStatus: "Urgent Backfill Initiative",
    },
    {
      requisitionId: "oc-41908",
      requisitionTitle: "Senior Manager, Global Logistics Optimization & Supply Operations",
      requisitionBadge: "Standard Role",
      requisitionDepartment: "supply-chain",
      requisitionDepartmentLabel: "International Freight & Procurement",
      requisitionLocation: "New York, NY",
      requisitionWorkplace: "hybrid",
      requisitionWorkplaceLabel: "Hybrid · 3 Days",
      requisitionCompensation: "$165,000 - $210,000 USD / yr + 15% Bonus",
      requisitionCompensationValue: 210000,
      requisitionEmploymentType: "fte",
      requisitionEmploymentLabel: "Full-Time · Permanent",
      requisitionPostedDays: 5,
      requisitionPostedLabel: "Posted 5 days ago",
      requisitionSeniority: "mid",
      requisitionSeniorityLabel: "Mid-Senior Level",
      requisitionIcon: "logistics",
      requisitionIconTone: "pale",
      requisitionQualifications: [
        "8+ years directing multi-modal global shipping channels handling more than $400M in annual cargo throughput.",
        "Proficiency with SAP S/4HANA Transportation Management, Oracle SCM Cloud, and digital customs programs.",
        "APICS/ASCM CSCP certification and experience mitigating trans-Pacific tariff and route disruption contingencies.",
      ],
      requisitionStatus: "Global Ops Division 12",
    },
    {
      requisitionId: "oc-73211",
      requisitionTitle: "Cloud Security Operations Manager",
      requisitionBadge: "Direct Opening",
      requisitionDepartment: "cloud",
      requisitionDepartmentLabel: "Cloud & Systems Architecture",
      requisitionLocation: "Austin, TX",
      requisitionWorkplace: "remote",
      requisitionWorkplaceLabel: "Fully Remote · US",
      requisitionCompensation: "$155,000 - $205,000 USD / yr + Bonus",
      requisitionCompensationValue: 205000,
      requisitionEmploymentType: "fte",
      requisitionEmploymentLabel: "Full-Time · Permanent",
      requisitionPostedDays: 6,
      requisitionPostedLabel: "Posted 6 days ago",
      requisitionSeniority: "mid",
      requisitionSeniorityLabel: "Mid-Senior Level",
      requisitionIcon: "cloud",
      requisitionIconTone: "blue",
      requisitionQualifications: [
        "6+ years operating cloud security programs across AWS and Azure environments.",
        "Experience with SIEM, incident response, IAM governance, and infrastructure-as-code security controls.",
        "CISSP, CCSP, or equivalent security certification preferred.",
      ],
      requisitionStatus: "Security Screening Active",
    },
    {
      requisitionId: "oc-62105",
      requisitionTitle: "Healthcare Data Platform Product Manager",
      requisitionBadge: "New Requisition",
      requisitionDepartment: "healthcare",
      requisitionDepartmentLabel: "Healthcare & Life Sciences",
      requisitionLocation: "Boston, MA",
      requisitionWorkplace: "hybrid",
      requisitionWorkplaceLabel: "Hybrid · 3 Days",
      requisitionCompensation: "$145,000 - $190,000 USD / yr",
      requisitionCompensationValue: 190000,
      requisitionEmploymentType: "fte",
      requisitionEmploymentLabel: "Full-Time · Permanent",
      requisitionPostedDays: 8,
      requisitionPostedLabel: "Posted 8 days ago",
      requisitionSeniority: "mid",
      requisitionSeniorityLabel: "Mid-Senior Level",
      requisitionIcon: "ai",
      requisitionIconTone: "pale",
      requisitionQualifications: [
        "5+ years managing healthcare data products across clinical, payer, or life sciences environments.",
        "Deep familiarity with HIPAA, FHIR, HL7, and data governance workflows.",
        "Proven ability to translate regulated customer needs into platform roadmaps.",
      ],
      requisitionStatus: "Hiring Manager Review",
    },
    {
      requisitionId: "oc-58872",
      requisitionTitle: "Senior Counsel, Privacy Engineering",
      requisitionBadge: "Corporate Governance",
      requisitionDepartment: "legal",
      requisitionDepartmentLabel: "Legal, Risk & Compliance Office",
      requisitionLocation: "Washington, DC",
      requisitionWorkplace: "global",
      requisitionWorkplaceLabel: "Global Remote · EMEA/APAC",
      requisitionCompensation: "$180,000 - $235,000 USD / yr",
      requisitionCompensationValue: 235000,
      requisitionEmploymentType: "contract",
      requisitionEmploymentLabel: "Direct Contract · W2",
      requisitionPostedDays: 12,
      requisitionPostedLabel: "Posted 12 days ago",
      requisitionSeniority: "lead",
      requisitionSeniorityLabel: "Lead / Principal",
      requisitionIcon: "legal",
      requisitionIconTone: "slate",
      requisitionQualifications: [
        "7+ years privacy counseling experience with a focus on product and engineering organizations.",
        "Working knowledge of GDPR, CCPA, AI regulation, and privacy-by-design practices.",
        "Excellent written communication for executive and technical audiences.",
      ],
      requisitionStatus: "Confidential Review",
    },
    {
      requisitionId: "oc-51008",
      requisitionTitle: "Supply Chain Analytics Associate",
      requisitionBadge: "Standard Role",
      requisitionDepartment: "supply-chain",
      requisitionDepartmentLabel: "Global Supply Chain",
      requisitionLocation: "Chicago, IL",
      requisitionWorkplace: "onsite",
      requisitionWorkplaceLabel: "On-site Headquarters",
      requisitionCompensation: "$82,000 - $112,000 USD / yr",
      requisitionCompensationValue: 112000,
      requisitionEmploymentType: "fte",
      requisitionEmploymentLabel: "Full-Time · Permanent",
      requisitionPostedDays: 18,
      requisitionPostedLabel: "Posted 18 days ago",
      requisitionSeniority: "entry",
      requisitionSeniorityLabel: "Entry Level",
      requisitionIcon: "logistics",
      requisitionIconTone: "pale",
      requisitionQualifications: [
        "2+ years working with operational data, inventory models, or transportation analytics.",
        "Strong SQL and spreadsheet modeling skills with a quantitative degree preferred.",
        "Clear communication and interest in global operations.",
      ],
      requisitionStatus: "Recruiter Review",
    },
    {
      requisitionId: "oc-47702",
      requisitionTitle: "Applied ML Research Intern",
      requisitionBadge: "Campus Program",
      requisitionDepartment: "healthcare",
      requisitionDepartmentLabel: "Healthcare & Life Sciences",
      requisitionLocation: "New York, NY",
      requisitionWorkplace: "onsite",
      requisitionWorkplaceLabel: "On-site Headquarters",
      requisitionCompensation: "$38 - $48 USD / hr",
      requisitionCompensationValue: 99840,
      requisitionEmploymentType: "fte",
      requisitionEmploymentLabel: "Internship · Campus",
      requisitionPostedDays: 21,
      requisitionPostedLabel: "Posted 21 days ago",
      requisitionSeniority: "internship",
      requisitionSeniorityLabel: "Internship / Campus",
      requisitionIcon: "ai",
      requisitionIconTone: "blue",
      requisitionQualifications: [
        "Currently pursuing a degree in computer science, statistics, biomedical engineering, or a related field.",
        "Coursework or project experience in Python, machine learning, and data analysis.",
        "Curiosity about responsible AI in healthcare and life sciences.",
      ],
      requisitionStatus: "Campus Recruiting",
    },
    {
      requisitionId: "oc-40126",
      requisitionTitle: "Enterprise FinTech Solutions Architect",
      requisitionBadge: "Priority Hire",
      requisitionDepartment: "fintech",
      requisitionDepartmentLabel: "Enterprise FinTech",
      requisitionLocation: "New York, NY",
      requisitionWorkplace: "remote",
      requisitionWorkplaceLabel: "Fully Remote · US",
      requisitionCompensation: "$175,000 - $235,000 USD / yr + Bonus",
      requisitionCompensationValue: 235000,
      requisitionEmploymentType: "contract",
      requisitionEmploymentLabel: "Direct Contract · W2",
      requisitionPostedDays: 27,
      requisitionPostedLabel: "Posted 27 days ago",
      requisitionSeniority: "lead",
      requisitionSeniorityLabel: "Lead / Principal",
      requisitionIcon: "finance",
      requisitionIconTone: "navy",
      requisitionQualifications: [
        "8+ years designing payment, treasury, or capital markets technology solutions.",
        "Experience with APIs, event-driven architecture, and enterprise integration patterns.",
        "Ability to partner with regulated financial institutions and technical executives.",
      ],
      requisitionStatus: "Priority Review",
    },
  ],
};
