import type { Articles01Data } from "./types";

/** Raw template content. Derived fields (e.g. `categories`) are computed in `page.tsx`. */
export const Articles01placeHolder: Articles01Data= {
  brandName: "GAZETTE",

  leadEyebrow: "Lead Monograph",
  leadPullQuote:
    "“Silence is not the mere absence of decibels, but the tactile presence of intentional void.”",
  leadArticle: {
    articleId: "lead-01",
    articleCategory: "architecture",
    articleCategoryLabel: "Architecture & Space",
    articleTitle: "The Architecture of Silence: Reclaiming Stillness in the Hyper-Dense Metropolis",
    articleExcerpt:
      "An inquiry into spatial minimalism, acoustic isolation, and the metaphysical weight of modern urban sanctuaries. How contemporary brutalist restoration allows the fragmented consciousness to settle beneath raw timber and poured stone.",
    articleByline: "By Julian Vance",
    articleReadTime: "16 min read",
    articleDate: "Autumn Monograph",
    articleIssue: "Issue Nº 142",
    articleImageUrl:
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=80&w=1200",
    articleImageAlt: "Monolithic concrete brutalist chamber with a single figure seated in sunlight",
    articlecaption: "Fig. 1.0 — Monolithic Concrete Chamber, Kyoto Prefecture. Archival Ref: GAZ-2024-88A",
  },

  broadsideEyebrow: "Gazette Editions & Cold-Press Folios",
  broadsideTitle: "The Physical Broadside: Folio 142",
  broadsideDescription:
    "Bound in Japanese thread-sewn bindings on 140gsm unbleached Munken Pure stock. Limited edition of 1,200 numbered copies worldwide, accompanied by archival hand-pulled copperplate prints.",
  broadsideBuyLabel: "Acquire Physical Folio — $38",
  broadsideSpecsLabel: "Colophon Specifications",

  articles: [
    {
      articleId: "art-01",
      articleCategory: "architecture",
      articleCategoryLabel: "Architecture & Space",
      articleTitle: "The Alpine Monasteries of Zumthor: Geometry Born from Mountain Granite",
      articleExcerpt: "Exploring the thermal baths and cliffside sanctuaries where materiality dissolves into ritualistic calm, framing mist through sharp hand-chiseled apertures.",
      articleByline: "By Helena Lindqvist",
      articleReadTime: "8 min read",
      articleDate: "Oct 14, 2024",
      articleIssue: "Issue 142.2",
      articleImageUrl: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&q=80&w=800",
      articleImageAlt: "Minimalist concrete staircase bathed in warm light",
    },
    {
      articleId: "art-02",
      articleCategory: "philosophy",
      articleCategoryLabel: "Philosophy & Thought",
      articleTitle: "On the Metaphysics of Handwriting: Ink, Paper Grain, and Retained Memory",
      articleExcerpt: "Why the cognitive drag of steel nibs dragging over heavy cotton stock preserves deliberate thought in an era of ephemeral algorithmic epigrams.",
      articleByline: "By Dr. Alistair Finch",
      articleReadTime: "11 min read",
      articleDate: "Oct 11, 2024",
      articleIssue: "Issue 142.3",
      articleImageUrl: "https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&q=80&w=800",
      articleImageAlt: "Antique desk with inkwell, fountain pen, and handwritten manuscript",
    },
    {
      articleId: "art-03",
      articleCategory: "culture",
      articleCategoryLabel: "Culture & Craft",
      articleTitle: "The Clay of Bizen: Kiln Ashes, Unvarnished Surfaces, and 800 Years of Fire",
      articleExcerpt: "A documentary monograph into Okayama's ancient wood-firing ceramicists who allow scorched pine ash to dictate the narrative contour of vessels.",
      articleByline: "By Evelyn Morro",
      articleReadTime: "14 min read",
      articleDate: "Oct 08, 2024",
      articleIssue: "Issue 142.4",
      articleImageUrl: "https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&q=80&w=800",
      articleImageAlt: "Raw ceramic vase on dark gallery pedestal",
    },
    {
      articleId: "art-04",
      articleCategory: "cinema",
      articleCategoryLabel: "Cinema & Motion",
      articleTitle: "Sculpting the Ineffable: Tarkovsky and the Temporality of Moving Frames",
      articleExcerpt: "Revisiting the seven-minute uncut panning shots of 'The Sacrifice' as metaphysical endurance tests against the accelerated cadence of consumer video.",
      articleByline: "By Soren Kjaer",
      articleReadTime: "10 min read",
      articleDate: "Oct 04, 2024",
      articleIssue: "Issue 142.5",
      articleImageUrl: "https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&q=80&w=800",
      articleImageAlt: "Cinematic film still with misty landscape",
    },
    {
      articleId: "art-05",
      articleCategory: "architecture",
      articleCategoryLabel: "Architecture & Space",
      articleTitle: "Acoustic Ecology: Designing Vaults for Pure Auditory Reflection",
      articleExcerpt: "How contemporary acoustic engineers in Oslo collaborate with timber conservators to craft spaces where whispered speech carries three hundred feet.",
      articleByline: "By Mia Cardone",
      articleReadTime: "9 min read",
      articleDate: "Sep 29, 2024",
      articleIssue: "Issue 142.6",
      articleImageUrl: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae?auto=format&fit=crop&q=80&w=800",
      articleImageAlt: "Vast wooden library hall with parallel sunbeams",
    },
    {
      articleId: "art-06",
      articleCategory: "philosophy",
      articleCategoryLabel: "Philosophy & Thought",
      articleTitle: "Chronometry and Consciousness: The Slowing of Interior Time",
      articleExcerpt: "An analysis of non-linear subjective durations experienced in remote monasteries and deep-sea research stations without circadian cues.",
      articleByline: "By Thomas W. Ward",
      articleReadTime: "15 min read",
      articleDate: "Sep 25, 2024",
      articleIssue: "Issue 142.7",
      articleImageUrl: "https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&q=80&w=800",
      articleImageAlt: "Intricate clockwork gears and pocket watch mechanism",
    },
  ],
};
