export type Category = "combos" | "ramen" | "sides" | "rice" | "dessert";
export type Product = { id: string; name: string; category: Category; price: number; description: string; tags: string[]; stock: "in" | "out"; badge?: string; badgeTone?: "yellow" | "orange" | "green" | "red"; code: string; imageUrl: string; imageAlt: string };

const images = [
  "https://lh3.googleusercontent.com/aida-public/AB6AXuCWEn8f3qSlvL4Jt-JSB5AApJvn8qrdmtPbiDiG0AksV8fQK85Cf848cXels3uJQ4nY05TTriICarZoDkiNIsaKRzCqaJhhx-fQ0RcZrb5GOK9G12pkUYn2vyiOU9F9ejcvkmng6jtrkEEdX4QL_TG7ktgkrKd25rnQ88oSHG1Jjkp_ZtiKf14awgpPORdlCWyKFk2SK3bJpNOJ8-rXns9FzV1AsJht8ZZ85MNnTMGFZ5U-vaVrMYlHw",
  "https://lh3.googleusercontent.com/aida-public/AB6AXuCfHdX_zRpFjXjXnQTRAS66Lh2Ve6V7hi_tIzCMN-r04RmEzDOx7YRp764iwQxG1vyr6z-74tXDL6XybOdXbUbWxWnYdn7SQJmArqiyAptgFky0LLH8EfNHqX_I5uzS0Pck-26OBNsP2welVBM_zxmjOlBTM5JJKgXiwsRcohWHdaQVqu59_yrT2AHL2DpHLS6dh1VdswpuaIScDbcNlGrYwKXPKACG9W0OOf3LUnTB7dOC2oD3YkuYkw",
  "https://lh3.googleusercontent.com/aida-public/AB6AXuCSOxVCmBSFGl-GZGlhhTrKMcIRIpvwpEoA0QJOO1710THSw0wM1Yar5A-pRmW_u1cq2x1_GWLWPRXFae1K7ksJNo5iDgvnKk1BlT2ekuOgm0NLQXTebPniClrILf4Nc2ZXD9Lf2Zy2phwF1ZxRKiGSy80JpsmgiJZV5fh_b1jNN70hney_hh_OnnB0AYGo8GVWv8hbG2LKCUY20_oG09eeIx41cTJ6Y7G2eJEyQcf-JKxxBFN6qvc09g",
  "https://lh3.googleusercontent.com/aida-public/AB6AXuBYkMnKG-XRhQ45ep3_DkKUuktADOGKctSLIgfZEZ3G2pcLtLvBu0P8KF-hDom1OJ0iaETQmqmcS-bGXVHIWLvJcZoteKwP9vFa6VgyBfN2DJXLjlIbqUAiN7AStBheR_pnmoxJ_MZvSG5Z1syB3VvcMvCPO-hcQf9GMffbBPfRaivFnEJ290HfT3KPmuzpeNerXbw5lGARscJMNBzn2ocpia9WfT16rYNREvlzSj-fR7EEE1-TYhIKmQ",
  "https://lh3.googleusercontent.com/aida-public/AB6AXuCLbrjZIDLRUoa9DZvZfzXZqkwfQj5D07OJjPmpsZgQJft8-AmWyj8XL5bbk9tk_L3aeNFqUuurSTcqgPrHRpFUFexSZlMBw9aMrS0818CIRQ0ZtjLUHVNT7TBQjlMX1uqPVCB6a5zw3eK5TxW-I6VR53sNfXkahBux7giVKXg4q9K8h4P-ZG4mbJTpKhy3JqGuzE-plPmKmkMFs6JfhS3_isZbtAlbzX-iTUgON1DiIYccTFaLLL8C1Q",
  "https://lh3.googleusercontent.com/aida-public/AB6AXuAs1sERyDAhbMeKGtvDaYkX2xVzlhDy6-MhdBHW_IyV3fB5V7X2GXaRWDO5RmQLbozpuOHzl0g2Ky5UZ3NEhC1UdQS2Kw_CUZHZgVNklmY75oDJwzv4IyqJcNCiD-ELqSe_HEnx0m3jIUKdGC-RiykVq2AkFRCWwyfFO-AZ99r73H-vuJH4K2w2D0JWXnvX035FXhaLYc5_tjz7uZtM-kKPvt70503p3iXqDVq6CraihP_krS3pauW-Ow",
  "https://lh3.googleusercontent.com/aida-public/AB6AXuBPtogEGnDZMwlNzm06hqUG5DRHu2txEjPI8odwofsTsmrUAZDNW_KuAOA7whrgTXmh3nnoheJAoF_PM7JmJjklLfu07p3vb3es7qo-sJMrmbqMvbW2ELcgmpcfr-jlmJuvWgYBPe9uVVJ_F_IzoaHNVC3avBBXkNQ0GUJwPV3TKqTGdPFZe--ykOUU_tu6l0BpDufmPi1g8JUbT7Vyhy9jxv0isuFb6WBud2MVZ1aSP-77TlAevNuSMw",
  "https://lh3.googleusercontent.com/aida-public/AB6AXuBHigwBs185YiR1AodFv2dTwzJ2vcU6dv3t_Dq9yt8DRfvSv8vIZOtVlBF4rXAeqGxRX174ZySmzROs2GVSmquBt6aY_gn8tCSBAa4AohGDr4VcumkpHTVq3Ve2zDbF16tgDFHnWRkWwZkSDYlY8nzvqVoET7m5qvjnSyW8TdW8eS2TvdRaTqTHLtCPrhhdB9jOgzsMcRwpmMhBq9zbIQyjYHWtaCL-bftmaK6QoyzbwDJaa9fiMDb8Og",
  "https://images.unsplash.com/photo-1553621042-f6e147245754?auto=format&fit=crop&q=80&w=900",
];

export const products: Product[] = [
  { id: "ramen-01", name: "Tokyo Black Garlic Tonkotsu", category: "ramen", price: 14.5, description: "Roasted black mayu garlic oil, 18-hour broth, thick house-cut noodles & melt-in-mouth pork chashu.", tags: ["spicy", "chef"], stock: "in", badge: "2X SPICY", badgeTone: "orange", code: "RECIPE #01", imageUrl: images[0], imageAlt: "Tokyo black garlic tonkotsu ramen" },
  { id: "sides-08", name: "Crispy Karaage Basket", category: "sides", price: 8.99, description: "Sake & ginger marinated free-range thigh pieces fried in potato starch with Japanese spicy mayo dip.", tags: ["chef", "classic"], stock: "in", badge: "ONLY 4 LEFT", badgeTone: "orange", code: "SIDE #08", imageUrl: images[1], imageAlt: "Crispy Japanese karaage chicken basket" },
  { id: "ramen-03", name: "Wagyu Beef Tsukemen", category: "ramen", price: 16.25, description: "Extra thick chilled artisanal noodles paired with an ultra-concentrated simmering A5 wagyu dipping gravy.", tags: ["chef"], stock: "in", badge: "HOT SELLER", badgeTone: "yellow", code: "DIP #03", imageUrl: images[2], imageAlt: "Wagyu beef tsukemen dipping noodles" },
  { id: "ramen-05", name: "Spicy Tantanmen", category: "ramen", price: 14.95, description: "Creamy white sesame broth, infused Szechuan chili oil, crushed peanuts, bok choy, and wok pork mince.", tags: ["spicy"], stock: "in", badge: "3X SPICY", badgeTone: "red", code: "RAMEN #05", imageUrl: images[3], imageAlt: "Spicy tantanmen ramen" },
  { id: "rice-02", name: "Salmon Teriyaki Don", category: "rice", price: 13.75, description: "Crispy skin grilled salmon over Koshihikari sushi rice, seasoned nori, pickled radishes, and sweet soy glaze.", tags: ["classic"], stock: "in", badge: "FRESH TODAY", badgeTone: "green", code: "BOWL #02", imageUrl: images[4], imageAlt: "Salmon teriyaki rice bowl" },
  { id: "dessert-04", name: "Matcha Soft Serve & Taiyaki", category: "dessert", price: 6.5, description: "Authentic Kyoto Uji ceremonial matcha creamy soft serve served alongside a fresh-baked red bean waffle.", tags: ["classic"], stock: "in", badge: "DESSERT SPOTLIGHT", badgeTone: "yellow", code: "SWEET #04", imageUrl: images[5], imageAlt: "Matcha soft serve with taiyaki" },
  { id: "ramen-09", name: "Volcano Fire Noodles", category: "ramen", price: 15.5, description: "Triple ghost pepper reduction, slow-simmered dashi tare, charred red chili pods, and thick spring noodles.", tags: ["spicy"], stock: "in", badge: "EXTREME SPICY 5X", badgeTone: "red", code: "FIRE #09", imageUrl: images[6], imageAlt: "Extreme spicy volcano fire noodles" },
  { id: "sides-06", name: "Takoyaki Balls (6 pcs)", category: "sides", price: 7.99, description: "Crisp exterior, molten dashi batter filled with tender octopus chunks, Japanese mayo, and dancing bonito flakes.", tags: ["classic", "chef"], stock: "in", badge: "STREET CLASSIC", badgeTone: "yellow", code: "OSAKA #06", imageUrl: images[7], imageAlt: "Osaka takoyaki balls" },
  { id: "ramen-10", name: "Truffle Mushroom Mazesoba", category: "ramen", price: 15, description: "Brothless umami noodles with black truffle butter, sauteed wild maitake mushrooms, and cured egg yolk.", tags: ["chef"], stock: "out", badge: "RESTOCK TOMORROW", badgeTone: "green", code: "SOLD OUT", imageUrl: images[8], imageAlt: "Truffle mushroom maz soba noodles" },
];

export const categories = [{ id: "all", label: "ALL (9)" }, { id: "combos", label: "🔥 COMBOS" }, { id: "ramen", label: "🍜 RAMEN" }, { id: "sides", label: "🍗 SIDES" }, { id: "rice", label: "🍚 RICE BOWLS" }, { id: "dessert", label: "🍦 DESSERTS" }];
